### ISSUE TITLE
ERROR: HLA type not found for Z1712369T hla-c03:100

### ISSUE THREAD

**Issue by ChengYunazhi** [MathOnco/NeoPredPipe#2]

**Comment by rschenck** [comment]
This is not proper nomenclature for HLA-C03 I believe. In addition because NeoPredPipe utilizes netMHCpan for Neoantigen predictions within the pipeline the HLA type must be supported by their list of HLA types (can be referenced here: http://www.cbs.dtu.dk/services/NetMHCpan/MHC_allele_names.txt or within the repository).
