### ISSUE TITLE
How use NeoPredPipe without HLA information? 

### ISSUE THREAD

**Issue by liminghao663** [MathOnco/NeoPredPipe#27]
In the published article,

"In cases where no HLA haplotype information is available the most common alleles of each haplotype are assessed; while in cases where the HLA haplotypes are homozygous only that HLA haplotype is used for prediction."

But how to set the **-H** parameter in running NeoPredPipe.py without HLA information? I have tried many times~~~~~~~

**Comment by elakatos** [comment]
Sorry for the late answer.

I haven't tried it explicitly without HLA types, but I think you could define an hla file with empty entries (or NA) instead of HLAs. So it would look something like
Patient   HLA_A1    HLA_A2
Sample1     NA    NA
(but with tabulators instead of spaces between the columns)
In this case the default HLA type to use is the most common one in caucasian population, HLA-A02:01. I haven't tested this case yet, so please let me know if it throws an error (something like HLA type not found or so).

Alternatively, you could use a set of HLAs that cover most of the population, but for this you'd have to input these into the hla type file:
https://help.iedb.org/hc/en-us/articles/114094151851-HLA-allele-frequencies-and-reference-sets-with-maximal-population-coverage
