### ISSUE TITLE
The meaning of some columns

### ISSUE THREAD

**Issue by wt12318** [MathOnco/NeoPredPipe#28]
Hi,

I use the following code to predict neoantigen :
```
NeoPredPipe.py -I ./test/ -H ./TCGA_HLA_typing.txt -o ./test_results -n TCGA-02-0047-01A -c 0 -E 8 9 10 -x exp/
```
The `test_result` directory contains the following files:
```
 ls

TCGA-02-0047-01A.neoantigens.Indels.summarytable.txt  TCGA-02-0047-01A.neoantigens.summarytable.txt
TCGA-02-0047-01A.neoantigens.Indels.txt               TCGA-02-0047-01A.neoantigens.txt
```
But this `TCGA-02-0047-01A.neoantigens.txt` file has some columns between `Identity` and `Binding Affinity` that I can not find in the Readme:

![image](https://user-images.githubusercontent.com/39486023/112429380-89f39a00-8d77-11eb-8644-10924d96ad6e.png)

What these columns stand for?

Thank you.

**Comment by wt12318** [comment]
[TCGA-02-0047-01A.neoantigens.txt](https://github.com/MathOnco/NeoPredPipe/files/6202509/TCGA-02-0047-01A.neoantigens.txt)

This is my output file.

**Comment by elakatos** [comment]
Hi,
Which version of netMHCpan have you used? The pipeline was primarily developed for netMHCpan4.0 and readme is for outputs gained from that. I believe netMHCpan4.1 includes additional columns, so my guess would be the extra columns come from this version?
In which case according to the netMHCpan4.1 documentation, columns V21-V25 should be these:
Score_EL, %Rank_EL, Score_BA, %Rank_BA,  Aff(nM).

I'll update the readme to clarify this difference.
Also, if you want to use the NeoRecoPo side of our pipeline too,  please keep in mind that you should format this output table to have the same columns (in the same order) as the netMHCpan4.0 output (shown in the readme), otherwise the downstream processing will not work.

Best,
Eszter

**Comment by wt12318** [comment]
Thank you for your prompt reply. Yes, I used netMHCpan4.1.
