### ISSUE TITLE
Indel not processing correctly

### ISSUE THREAD

**Issue by RTCarmo** [MathOnco/NeoPredPipe#37]
Hello, thanks for the fantastic tool!
I have been using it for many years, but I am facing a bug I have never encountered.

I am running Neopredpipe for a set of samples, separating them by SNPs and indels. The SNP prediction ran smoothly. But, for indels, I got the following error:

> INFO: Summary Tables Complete.
> Traceback (most recent call last):
>   File "/home/tools/manual/NeoPredPipe/NeoPredPipe.py", line 524, in <module>
>     main()
>   File "/home/tools/manual/NeoPredPipe/NeoPredPipe.py", line 516, in main
>     FinalOut(t, Options, True)
>   File "/home/tools/manual/NeoPredPipe/NeoPredPipe.py", line 278, in FinalOut
>     appendedEps = getattr(sampleClasses[i],epitopesToProcess)
> AttributeError: Sample instance has no attribute 'appendedEpitopesIndels'

Checking the log, all samples got the following:

> INFO: ANNOVAR Ready files for ROP-76 already present.
> INFO: ANNOVAR Annotation files for ROP-76 already present.
> INFO: Coding change fasta files for ROP-76 already present.
> INFO: Coding change fasta files ROP-76 has already been reformatted.
> INFO: Epitope prediction files ROP-76 have already been created for netMHCpan length 9.Indels.
> INFO: Predicting neoantigens for ROP-76
> INFO: Skipping Sample! No peptides to predict for ROP-76
> INFO: Running Epitope Predictions for ROP-76 on epitopes of length 9.Indels
> INFO: Predictions complete for ROP-76 on epitopes of length 9.Indels
> INFO: Digesting neoantigens for ROP-76
> INFO: Object size of neoantigens: 5504 Kb

Although it says that the samples are being skipped, the fasta files, tmp files, avannotated files, and avready are not empty. A quick inspection of the tmp files showed that there are both wb and sb neoantigens being predicted, which suggests that, for some reason, the selection step from tmp files is not running correctly... 

Can you help me? There are any lines that I could run to simply extract the information and generate both .neoantigens.txt and .neoantigens.summarytable.txt?

**Comment by elakatos** [comment]
Hi!
The error message you get is a known bug we have, when there are no indels predicted at all and it slightly breaks down the table processing step (we will aim to fix this!).
So the issue really is why it would think there are no indels predicted... According to the log file lines you copied in here, it does predict some indels: the "skipping sample" part means for one particular length (maybe 10-long indels) it is skipping, but according to the next line, it is running for 9-long indels, and indeed there are predictions being read in (otherwise the object size would be much smaller).
Just to make sure you have most up-to-date files, can you rerun after deleting the tmp folder (to get new neoantigen predictions)? And then could you share the command you run and the full logfile?

If you want to ensure you have neoantigens.txt and don't mind doing postprocessing on it yourself, you could use the -a option to report all peptides in the output table, not only SB/WB ones - so as long as you have any peptides to predict from, you would get an output.
