### ISSUE TITLE
Can this pipeline predict the Neoantigen with HLA class II data？

### ISSUE THREAD

**Issue by Tiredbird** [MathOnco/NeoPredPipe#9]
Hello all，
I read your paper today and I am interesting with your pipeline. But I find netMHCpan, but no netMHCIIpan. Does it mean that  we can't deal with the HLA class II data using the Pipeline? Is that right?

Best

**Comment by rschenck** [comment]
Currently this isn’t a part of NeoPredPipe, but it should not be difficult to modify slightly to use it for this purpose. We have plans to include this in the very near future. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tiredbird** [comment]
Thanks a lot. I'm looking forward to the new version of the pipeline.

**Comment by elakatos** [comment]
Hi!
Actually, I've added support for netMHCIIpan, but it hasn't been thoroughly tested (and hence not added to the documentation), so keep in mind that it might have some issues.
You can simply specify a path to netMHCIIpan in the user-defined paths file (instead of netMHCpan) and NeoPredPipe should detect that type-II prediction is required. (I've tested it with the latest netMHCIIpan version, 3.2, but I think anything should work as long as the actual executable is called netMHCIIpan.) Also, set the predicted epitope-length accordingly (-E 15).

The major computational difference between HLA type-I and type-II comes from processing the HLA haplotyping outputs themselves. For type-II, you can define HLA types in two ways:
1) Similarly to type-I, a tab-separated file with the patient name first and then a tab-separated list of HLA-types (order doesn't matter)
2) A directory, in which there is a subdirectory named as the individual samples, containing the prediction output of a) HLAminder or b) HLA-HD. The folder test/hla-II has one example each of the supported prediction outputs.
In each case, NeoPredPipe assumes that the haplotyping file contains separate DPA1/DQA1 and DPB1/DPQ1 predictions and generates all linear combinations to fit with haplotypes covered in netMHCIIpan. It will also output a warning if a haplotype is not covered by netMHCIIpan and therefore ignored, but will proceed with the covered haplotypes.

Let us know how the type-II prediction works and if you encounter any issues.

**Comment by rschenck** [comment]
I'm going to mark this as an enhancement and leave it open so others can see it for now to know it's in beta for supporting HLA type-II

**Comment by Tiredbird** [comment]
Hi
I used netMHCIIpan to instead of netMHCpan in the usr_paths.ini. And It worked. 
Thank you very much.
I will test it on more samples.
